### PR TITLE
Added some new simple but versatile functions

### PR DESCRIPTION
**Pull request by AshbornXS**
got all functions from [TachiyomiS97](https://github.com/Saud-97/TachiyomiS97) so all credits go to [Saud-97](https://github.com/Saud-97), in my opinion they are some pretty good functions to have even thought pretty simple, if liked feel free to use

### CODE REVIEW

**Comment by AshbornXS** [comment]
oops discart the updates to readme, idk how to remove it

**Comment by null2264** [comment]
Idk about "long tap browse source to uninstall", I think the browse list shouldn't be used to manage extensions, and "auto fetch chapters on browse" seems like an unnecessary load for the source.

For the rest of them I think it's fine. Although I'm still debating about long tap on recents and browser nav, that could potentially disturbing someone's muscle memory.

**Comment by AshbornXS** [comment]
that makes sense, "auto fetch chapters on browse" is a toggle so by default isn't a load, it is by option, and for the long tap maybe put a toggle to enable/disable them? I think at least the recents one is pretty cool

**Comment by null2264** [comment]
Yeah, I'm not comfortable of adding toggle for "auto fetch chapters on browse"... But I could add the long tap nav as an option.

**Comment by null2264** [comment]
Merged as https://github.com/null2264/yokai/commit/b4638017dd774d9dcd325258611f663083493015

**Pull request closed without merging**
